/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as RandomSessionRouteImport } from './routes/random-session'
import { Route as RandomHistoryRouteImport } from './routes/random-history'
import { Route as ParagraphsRouteImport } from './routes/paragraphs'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SessionParagraphIdRouteImport } from './routes/session.$paragraphId'
import { Route as RandomHistorySessionIdRouteImport } from './routes/random-history.$sessionId'

const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RandomSessionRoute = RandomSessionRouteImport.update({
  id: '/random-session',
  path: '/random-session',
  getParentRoute: () => rootRouteImport,
} as any)
const RandomHistoryRoute = RandomHistoryRouteImport.update({
  id: '/random-history',
  path: '/random-history',
  getParentRoute: () => rootRouteImport,
} as any)
const ParagraphsRoute = ParagraphsRouteImport.update({
  id: '/paragraphs',
  path: '/paragraphs',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionParagraphIdRoute = SessionParagraphIdRouteImport.update({
  id: '/session/$paragraphId',
  path: '/session/$paragraphId',
  getParentRoute: () => rootRouteImport,
} as any)
const RandomHistorySessionIdRoute = RandomHistorySessionIdRouteImport.update({
  id: '/$sessionId',
  path: '/$sessionId',
  getParentRoute: () => RandomHistoryRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/analytics': typeof AnalyticsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/paragraphs': typeof ParagraphsRoute
  '/random-history': typeof RandomHistoryRouteWithChildren
  '/random-session': typeof RandomSessionRoute
  '/register': typeof RegisterRoute
  '/review': typeof ReviewRoute
  '/random-history/$sessionId': typeof RandomHistorySessionIdRoute
  '/session/$paragraphId': typeof SessionParagraphIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/analytics': typeof AnalyticsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/paragraphs': typeof ParagraphsRoute
  '/random-history': typeof RandomHistoryRouteWithChildren
  '/random-session': typeof RandomSessionRoute
  '/register': typeof RegisterRoute
  '/review': typeof ReviewRoute
  '/random-history/$sessionId': typeof RandomHistorySessionIdRoute
  '/session/$paragraphId': typeof SessionParagraphIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/analytics': typeof AnalyticsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/paragraphs': typeof ParagraphsRoute
  '/random-history': typeof RandomHistoryRouteWithChildren
  '/random-session': typeof RandomSessionRoute
  '/register': typeof RegisterRoute
  '/review': typeof ReviewRoute
  '/random-history/$sessionId': typeof RandomHistorySessionIdRoute
  '/session/$paragraphId': typeof SessionParagraphIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/analytics'
    | '/leaderboard'
    | '/login'
    | '/paragraphs'
    | '/random-history'
    | '/random-session'
    | '/register'
    | '/review'
    | '/random-history/$sessionId'
    | '/session/$paragraphId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/analytics'
    | '/leaderboard'
    | '/login'
    | '/paragraphs'
    | '/random-history'
    | '/random-session'
    | '/register'
    | '/review'
    | '/random-history/$sessionId'
    | '/session/$paragraphId'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/analytics'
    | '/leaderboard'
    | '/login'
    | '/paragraphs'
    | '/random-history'
    | '/random-session'
    | '/register'
    | '/review'
    | '/random-history/$sessionId'
    | '/session/$paragraphId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AnalyticsRoute: typeof AnalyticsRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LoginRoute: typeof LoginRoute
  ParagraphsRoute: typeof ParagraphsRoute
  RandomHistoryRoute: typeof RandomHistoryRouteWithChildren
  RandomSessionRoute: typeof RandomSessionRoute
  RegisterRoute: typeof RegisterRoute
  ReviewRoute: typeof ReviewRoute
  SessionParagraphIdRoute: typeof SessionParagraphIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/random-session': {
      id: '/random-session'
      path: '/random-session'
      fullPath: '/random-session'
      preLoaderRoute: typeof RandomSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/random-history': {
      id: '/random-history'
      path: '/random-history'
      fullPath: '/random-history'
      preLoaderRoute: typeof RandomHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paragraphs': {
      id: '/paragraphs'
      path: '/paragraphs'
      fullPath: '/paragraphs'
      preLoaderRoute: typeof ParagraphsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/$paragraphId': {
      id: '/session/$paragraphId'
      path: '/session/$paragraphId'
      fullPath: '/session/$paragraphId'
      preLoaderRoute: typeof SessionParagraphIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/random-history/$sessionId': {
      id: '/random-history/$sessionId'
      path: '/$sessionId'
      fullPath: '/random-history/$sessionId'
      preLoaderRoute: typeof RandomHistorySessionIdRouteImport
      parentRoute: typeof RandomHistoryRoute
    }
  }
}

interface RandomHistoryRouteChildren {
  RandomHistorySessionIdRoute: typeof RandomHistorySessionIdRoute
}

const RandomHistoryRouteChildren: RandomHistoryRouteChildren = {
  RandomHistorySessionIdRoute: RandomHistorySessionIdRoute,
}

const RandomHistoryRouteWithChildren = RandomHistoryRoute._addFileChildren(
  RandomHistoryRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AnalyticsRoute: AnalyticsRoute,
  LeaderboardRoute: LeaderboardRoute,
  LoginRoute: LoginRoute,
  ParagraphsRoute: ParagraphsRoute,
  RandomHistoryRoute: RandomHistoryRouteWithChildren,
  RandomSessionRoute: RandomSessionRoute,
  RegisterRoute: RegisterRoute,
  ReviewRoute: ReviewRoute,
  SessionParagraphIdRoute: SessionParagraphIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
