/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as ParagraphsRouteImport } from './routes/paragraphs'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SessionParagraphIdRouteImport } from './routes/session.$paragraphId'

const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const ParagraphsRoute = ParagraphsRouteImport.update({
  id: '/paragraphs',
  path: '/paragraphs',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionParagraphIdRoute = SessionParagraphIdRouteImport.update({
  id: '/session/$paragraphId',
  path: '/session/$paragraphId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/paragraphs': typeof ParagraphsRoute
  '/review': typeof ReviewRoute
  '/session/$paragraphId': typeof SessionParagraphIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/paragraphs': typeof ParagraphsRoute
  '/review': typeof ReviewRoute
  '/session/$paragraphId': typeof SessionParagraphIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/paragraphs': typeof ParagraphsRoute
  '/review': typeof ReviewRoute
  '/session/$paragraphId': typeof SessionParagraphIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/leaderboard'
    | '/paragraphs'
    | '/review'
    | '/session/$paragraphId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/leaderboard'
    | '/paragraphs'
    | '/review'
    | '/session/$paragraphId'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/leaderboard'
    | '/paragraphs'
    | '/review'
    | '/session/$paragraphId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  LeaderboardRoute: typeof LeaderboardRoute
  ParagraphsRoute: typeof ParagraphsRoute
  ReviewRoute: typeof ReviewRoute
  SessionParagraphIdRoute: typeof SessionParagraphIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paragraphs': {
      id: '/paragraphs'
      path: '/paragraphs'
      fullPath: '/paragraphs'
      preLoaderRoute: typeof ParagraphsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/$paragraphId': {
      id: '/session/$paragraphId'
      path: '/session/$paragraphId'
      fullPath: '/session/$paragraphId'
      preLoaderRoute: typeof SessionParagraphIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  LeaderboardRoute: LeaderboardRoute,
  ParagraphsRoute: ParagraphsRoute,
  ReviewRoute: ReviewRoute,
  SessionParagraphIdRoute: SessionParagraphIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
